
Let's create the GitHub Actions workflow file:

<div class="__boltArtifact__" data-artifact-id="11:github-workflow" data-running-actions="true"></div>

Now, let's update the Vite config to support GitHub Pages deployment:

<div class="__boltArtifact__" data-artifact-id="12:vite-config-update" data-running-actions="true"></div>

